
GET http://localhost:8080/ping HTTP/1.1

###
GET http://localhost:8080/devices/erer HTTP/1.1

###

GET http://localhost:8080/devices/000000007920365c HTTP/1.1

###

PATCH http://localhost:8080/devices/000000007920365b?lock=true HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:8080/devices/000000007920365b?lock=false HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:8080/devices/000000007920365b?black=true HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:8080/devices/000000007920365b?black=false HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/devices HTTP/1.1
Content-Type: application/json

{
    "user":"kneeru@gmail.com",
    "hw":"BCM2835",
    "serial":"000000007920365c",
    "model":"Raspberry Pi 3 Model B Rev 1.2"
}

###

GET http://localhost:8080/users/kneeru@gmail.com HTTP/1.1

###

POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "email":"kneeru@gmail.com",
    "role":2,
    "passwd":"ranjan_wati@538",
    "name":"Niranjan Awati",
    "phone":"+91 5453500 5435345",
    "loc":"Pune, 411057"
}

###
DELETE http://localhost:8080/users/kneeru@gmail.com HTTP/1.1


###
PUT http://localhost:8080/users/kneeru@gmail.com HTTP/1.1
Content-Type: application/json

{
    "email":"kneeru@gmail.com",
    "name":"Niranjan Vijay Awati",
    "phone":"+91 5453500 65654654",
    "loc":"Pune, 411038"
}

### 
PATCH http://localhost:8080/users/kneeru@gmail.com HTTP/1.1
Content-Type: application/json

{
    "email":"kneeru@gmail.com",
    "passwd":"iranjan_%41993"
}
### 
PATCH http://localhost:8080/users/kneeru@gmail.com HTTP/1.1
Content-Type: application/json

{
    "email":"niranjan@gmail.com",
    "passwd":"iranjan_%41993"
}

### 
PATCH http://localhost:8080/users/kneeru@gmail.com HTTP/1.1
Content-Type: application/json

{
     "email":"kneeru@gmail.com",
    "passwd":"iranjan_%41993$#%$#%$#DFDFGDDFGDFG"
}

### 

POST http://localhost:8080/authenticate/kneeru@gmail.com
Content-Type: application/json

{
    "email":"kneeru@gmail.com",
    "passwd":"iranjan_%41993"
}

### 
GET http://localhost:8080/authorize?lvl=0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMwNDE1MzgsInJvbGUiOjAsInVzZXIiOiJrbmVlcnVAZ21haWwuY29tIiwidXVpZCI6IjZkYTlhOWVhLTU3N2QtNGNjMC1hMGZkLTAxM2I2MzgyZGQxZiJ9.NmWH-MChMmGKrTSDFoiVCrY2RRMyMd6OMfiBGv5puUo

###

GET http://localhost:8080/authorize?refresh=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMwNDE2MDgsInJvbGUiOjAsInVzZXIiOiJrbmVlcnVAZ21haWwuY29tIiwidXVpZCI6ImU3ODRjNjU5LTkxYWUtNGYwYy05MDZiLTRlYmVkZmM3MjMxZSJ9.y3XfC7TSULQr-h5ZW00k5mmztGXaBdw9fSGoC3AnBzc

###

DELETE  http://localhost:8080/authorize
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMwNDE2MDgsInJvbGUiOjAsInVzZXIiOiJrbmVlcnVAZ21haWwuY29tIiwidXVpZCI6ImU3ODRjNjU5LTkxYWUtNGYwYy05MDZiLTRlYmVkZmM3MjMxZSJ9.y3XfC7TSULQr-h5ZW00k5mmztGXaBdw9fSGoC3AnBzc