version: '3.1'

services:
    srvmongo:
      image: mongo:4.2-bionic
      ports:
          - 37017:27017
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: root
      #   MONGO_INITDB_ROOT_PASSWORD: example
      #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      tty: true
      stdin_open: true
      container_name: authapi_mongo
    srvredis:
      image: redis:6.0
      # ports:
      #   - 6379:6379
      tty: true
      stdin_open: true
      container_name: authapi_redis
      volumes: 
        - "/data:/data" # this is where redis will store its AOF appendonly file for persistence
    srvapi:
      build: .
      volumes:
        - .:/root/go/src/app
        - /var/local/authapi:/var/local/authapi # log and config files
      ports:
        - 80:8080
      stdin_open: true
      tty:  true
      links:
        - "srvmongo"
        - "srvredis"
      secrets:
        - auth_secrets
        - admin_secret
      container_name: authapi
      entrypoint: ["go", "run", ".", "-flog=true", "-verbose=true"]
secrets:
  auth_secrets:
    file: ./api.secret
  admin_secret:
    file: ./admin.secret