version: '3.1'

services:
    srvmongo:
        image: mongo:4.2-bionic
        restart: always
        ports:
            - 37017:27017
        # environment:
        #   MONGO_INITDB_ROOT_USERNAME: root
        #   MONGO_INITDB_ROOT_PASSWORD: example
        #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        tty: true
        stdin_open: true
        container_name: lumin_mongo
    srvlumin:
        build: .
        volumes:
          - .:/root/go/src/app
        ports:
          - 8080:8080
        stdin_open: true
        tty:  true
        links:
          - "srvmongo"
        container_name: lumin_api
        entrypoint: ["go", "run", "main.go"]